name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed the following
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation to ensure this feature doesn't already exist
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: API Design (if applicable)
      description: What would the API look like for this feature?
      render: typescript
      placeholder: |
        // Example API design
        const { form } = useForm({
          // Your proposed API here...
        });
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Which package(s) would this affect?
      multiple: true
      options:
        - el-form-core
        - el-form-react
        - el-form-react-hooks
        - el-form-react-components
        - Documentation
        - New package
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe any alternative approaches you've thought about...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help with documentation
        - label: I would be willing to help with testing
