name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zod: ["^3.22.0", "^4.0.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Set Zod version to ${{ matrix.zod }}
        run: pnpm add -w zod@${{ matrix.zod }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build workspace
        run: pnpm -w -r build

      - name: Test core (vitest)
        run: pnpm --filter el-form-core test -- --run

      - name: Test react-hooks (runtime + tsd)
        run: pnpm --filter el-form-react-hooks test
